require:
   - rubocop-rails
   - rubocop-rspec
   - rubocop-rspec_rails
   - rubocop-factory_bot

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - config/environments/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

