require:
   - rubocop-rails
   - rubocop-rspec
   - rubocop-rspec_rails

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - config/environments/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
