require:
   - rubocop-rails
   - rubocop-rspec
   - rubocop-rspec_rails
   - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - config/environments/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Rails/BulkChangeTable:
  Exclude:
    - db/migrate/20240723144726_add_devise_to_users.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/Documentation:
  Exclude:
    - db/migrate/*
